---
- name: restart mysql
  service: name=mysql state=restarted enabled=yes

- name: restart apache2
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - apache2
    - memcached
