---
- include_vars: "{{ item }}"
  with_first_found:
   - "../vars/{{ ansible_distribution }}.yml"
   - "../vars/{{ ansible_os_family }}.yml"
   - "../vars/default.yml"

- include: install.yml

- name: Insert webapp config
  template: src=csd_webconf.xqm.j2
            dest={{openinfoman_dir}}/repo/com/github/openhie/openinfoman/csd_webconf.xqm

# Flush handlers before updating
- meta: flush_handlers

- name: Complete ihris install
  shell: "php {{ihris_dir}}/sites/openhie-pr-site/pages --update=1;"
