---
- include_vars: "{{ item }}"
  with_first_found:
   - "../vars/{{ ansible_distribution }}.yml"
   - "../vars/{{ ansible_os_family }}.yml"
   - "../vars/default.yml"

# Install required packages
- name: Install required pacakges(Debian)
  apt: name={{item}}
       state=installed
       update_cache=yes
  with_items:
   - openjdk-7-jre-headless
   - git
   - unzip
   - apache2
   - mysql-server
   - mysql-client
   - python-mysqldb
   - php5
   - libapache2-mod-php5
   - php5-mysql
   - php5-xsl
   - xsltproc
   - php5-curl
   - bzr
   - php-mdb2
   - php-mdb2-driver-mysql
   - php-apc
   - memcached
   - php5-memcached
  notify: restart apache2
  when: ansible_os_family == 'Debian'

- name: Get latest BaseX snapshot
  get_url: url=http://files.basex.org/releases/BaseX-latest.zip
           dest=/tmp

- name: Unzip BaseX
  unarchive: creates={{basex_dir}}/basex
             copy=no 
             src=/tmp/BaseX-latest.zip
             dest={{basex_dir}}

- name: Make iHRIS dir
  file: state=directory
        path={{ihris_dir}}

- name: Checkout i2ce code
  bzr: name=lp:i2ce/4.2
       dest={{ihris_dir}}/i2ce 

- name: Checkout ihris code
  bzr: name=lp:ihris-common/4.2
       dest={{ihris_dir}}/ihris-common 

- name: Checkout openhie-pr
  bzr: name=lp:openhie-pr
       dest={{ihris_dir}}/openhie-pr

- include: install.yml
  when: not openinfoman_deploy

- include: deploy.yml
  when: openinfoman_deploy

- name: Create user to run basex
  user: name={{basex_user}}
        state=present
        createhome=no
        shell=/bin/sh
        system=yes
  notify: lock user

- name: Install basex service
  template: src=basex.j2
            dest=/etc/init.d/basex
            mode=0755
            owner=root
            group=root

# Insert configs

- name: Create config dir for openhie-pr
  file: path={{ihris_dir}}/openhie-pr/sites/basex/pages/local
        state=directory

- name: Insert config for openhie-pr
  template: src=config.values.php.j2
            dest={{ihris_dir}}/openhie-pr/sites/basex/pages/local/config.values.php

- name: Insert webapp config
  template: src=csd_webapp_config.xqm.j2
            dest={{openinfoman_dir}}/repo/csd_webapp_config.xqm

- name: Insert web.xml config
  template: src=web.xml.j2
            dest={{basex_dir}}/basex/webapp/WEB-INF/web.xml
  notify: restart basex

- name: Insert php-apc config
  template: src=apc.ini.j2
            dest=/etc/php5/conf.d/apc.ini
            owner=root
            group=root
            mode=0744
  notify: restart apache2

# DB config
- name: Set log_bin_trust_function_creators in my.cnf
  lineinfile: dest=/etc/mysql/my.cnf state=present
              regexp=^log_bin_trust_function_creators= 
              line=log_bin_trust_function_creators=1
  notify: restart mysql

- name: Set DB root password
  mysql_user: name=root
              password={{openinfoman_db_root_pwd}}
              login_user=root
              login_password={{openinfoman_db_root_pwd}}
              check_implicit_admin=yes
              state=present

- name: Create csd_hwr db
  mysql_db: name=csd_hwr
            encoding=utf8
            login_user=root
            login_password={{openinfoman_db_root_pwd}}
            state=present

- name: Create ihris db user
  mysql_user: name=ihris
              password={{openinfoman_db_ihris_pwd}}
              login_user=root
              login_password={{openinfoman_db_root_pwd}}
              priv=csd_hwr.*:ALL
              state=present

- name: Create the XML DB
  command: '{{basex_dir}}/basex/bin/basex -Vc "CREATE DATABASE provider_directory"'

- name: Link Openinfoman libs to basex
  shell: "ln -sf {{openinfoman_dir}}/repo/* {{basex_dir}}/basex/repo/; ln -sf {{openinfoman_hwr_dir}}/repo/* {{basex_dir}}/basex/repo/;"

- name: Link Administrative Interface
  shell: "ln -sf {{openinfoman_dir}}/webapp/*xqm {{basex_dir}}/basex/webapp/; ln -sf {{openinfoman_dir}}/webapp/static/* {{basex_dir}}/basex/webapp/static/;"

- name: Make available under apache
  shell: "ln -sf {{ihris_dir}}/openhie-pr/sites/basex/pages /var/www/openhie-hwr"

- name: Set proper permissions for apache
  file: path={{ihris_dir}}
        group=www-data
        owner=www-data
        recurse=yes
        state=directory

- name: Set basex permissions
  file: path={{item}} 
        owner={{basex_user}}
        group={{basex_user}}
        recurse=yes
  with_items:
    - "{{basex_dir}}/basex"
    - "{{openinfoman_dir}}"
    - "{{openinfoman_hwr_dir}}"

- include: data.yml
  when: openinfoman_demo_data

# Flush handlers before updating
- meta: flush_handlers

- name: Complete ihris install
  shell: "php {{ihris_dir}}/openhie-pr/sites/basex/pages/index.php --update=1; php {{ihris_dir}}/openhie-pr/sites/basex/pages/index.php --update=1;"
