---
- name: restart apache2
  service: name=apache2 state=restarted

- name: restart basex
  service: name=basex state=restarted

- name: restart mysql
  service: name={{mysql_service_name}} state=restarted

- name: lock user
  command: passwd -l basex
