---
# DB config
- name: set log_bin_trust_function_creators in my.cnf
  lineinfile: dest=/etc/mysql/my.cnf state=present regexp=^log_bin_trust_function_creators= line=log_bin_trust_function_creators=1
  notify: restart mysql

- name: Set DB root password
  mysql_user: name=root password={{ mysqlrootpwd }} login_user=root login_password={{ mysqlrootpwd }} check_implicit_admin=yes state=present

- name: Create csd_hwr db
  mysql_db: name=csd_hwr encoding=utf8 login_user=root login_password={{ mysqlrootpwd }} state=present

- name: create ihris db user
  mysql_user: name=ihris password={{ mysqluserpwd }} login_user=root login_password={{ mysqlrootpwd }} priv=csd_hwr.*:ALL state=present

# App config
- name: create config dir for openhie-pr
  file: path=/opt/ihris/openhie-pr/sites/basex/pages/local state=directory

- name: insert config for openhie-pr
  template: src=config.values.php dest=/opt/ihris/openhie-pr/sites/basex/pages/local/config.values.php

- name: set proper permissions for apache2
  file: path=/opt/ihris group=www-data owner=www-data recurse=yes state=directory

- name: Make available under apache
  shell: "ln -sf /opt/ihris/openhie-pr/sites/basex/pages /var/www/openhie-hwr"

- name: Complete ihris install
  shell: "php /opt/ihris/openhie-pr/sites/basex/pages/index.php --update=1; php /opt/ihris/openhie-pr/sites/basex/pages/index.php --update=1;"
  notify: restart apache2
