---
- name: Install required packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - apache2
    - mysql-server
    - mysql-client
    - php5
    - libapache2-mod-php5
    - php5-mysql
    - php5-xsl
    - xsltproc
    - php5-curl
    - bzr
    
- name: Make iHRIS dir
  file: state=directory path=/opt/ihris

- name: checkout i2ce code
  bzr: name=lp:~intrahealth+informatics/i2ce/4.2-dev dest=/opt/ihris/i2ce version=I2CE

- name: checkout ihris code
  bzr: name=lp:~intrahealth+informatics/ihris-common/4.2-dev dest=/opt/ihris/ihris-common version=ihris-common

- name: checkout openhie-pr
  bzr: name=lp:~intrahealth+informatics/openhie-pr dest=/opt/ihris/openhie-pr

