---
- name: Install required packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - apache2
    - mysql-server
    - mysql-client
    - python-mysqldb
    - php5
    - libapache2-mod-php5
    - php5-mysql
    - php5-xsl
    - xsltproc
    - php5-curl
    - bzr
    - php-mdb2
    - php-mdb2-driver-mysql
  notify: restart apache2
    
- name: Make iHRIS dir
  file: state=directory path=/opt/ihris

- name: checkout i2ce code
  bzr: name=lp:i2ce/4.2 dest=/opt/ihris/i2ce 

- name: checkout ihris code
  bzr: name=lp:ihris-common/4.2 dest=/opt/ihris/ihris-common 

- name: checkout openhie-pr
  bzr: name=lp:openhie-pr dest=/opt/ihris/openhie-pr

